name: Publish Docker image

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:

  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        push: true
        target: linux/arm64
        tags: ${{ github.repository }}:${{ github.ref }}

