# docker-image.yml
name: Publish Docker image to GitHub Container Registry

on:  
 push:
  branches:  # master分支有push时触发此workflow
   - 'master'
  tags:    # tag更新时触发此workflow
   - '*'

jobs:

 push_to_registry:  
  name: Push Docker image to GitHub Container Registry
  runs-on: ubuntu-latest  

  steps:
   - name: Check out the repo
    uses: actions/checkout@v2

   - name: Log in to GitHub Container Registry
    uses: docker/login-action@v2
    with:
     registry: ghcr.io
     token: ${{ secrets.GITHUB_TOKEN }}

   - uses: jungwinter/split@v2
    id: split
    with:
     msg: ${{ github.repository }}
     separator: "/"

   - name: Extract metadata (tags, labels) for Docker
    id: meta
    uses: docker/metadata-action@v3
    with:
     images: ${{ github.repository }}

   - name: Build and push Docker image
    uses: docker/build-push-action@v2
    with:
     file: Dockerfile
     push: true
     platforms: linux/arm64
     tags: ${{ steps.meta.outputs.tags }}
     labels: ${{ steps.meta.outputs.labels }}
